// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "Supabase environment variables are missing. Check NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.",
  );
}

let browserClient: SupabaseClient<Database> | null = null;

export const getSupabaseClient = () => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error("Las credenciales de Supabase no estan configuradas en el entorno.");
  }

  if (typeof window === "undefined") {
    throw new Error("Supabase solo puede inicializarse en el cliente del navegador.");
  }

  if (!browserClient) {
    browserClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: window.localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });
  }

  return browserClient;
};

export const supabase =
  typeof window !== "undefined" && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY ? getSupabaseClient() : null;
